# Generated by Django 5.1.3 on 2024-11-17 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('c_cname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('c_population', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('ds_disease_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ds_pathogen', models.CharField(blank=True, max_length=20, null=True)),
                ('ds_description', models.CharField(blank=True, max_length=140, null=True)),
            ],
            options={
                'db_table': 'disease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('dt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_description', models.CharField(blank=True, max_length=140, null=True)),
            ],
            options={
                'db_table': 'disease_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_email', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('u_name', models.CharField(blank=True, max_length=30, null=True)),
                ('u_surname', models.CharField(blank=True, max_length=40, null=True)),
                ('u_salary', models.IntegerField(blank=True, null=True)),
                ('u_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('dr_cname', models.OneToOneField(db_column='dr_cname', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='website.country')),
                ('dr_first_enc_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discover',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specialize',
            fields=[
                ('s', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='website.diseasetype')),
            ],
            options={
                'db_table': 'specialize',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('dc_email', models.OneToOneField(db_column='dc_email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='website.users')),
                ('dc_degree', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientDisease',
            fields=[
                ('pd_email', models.OneToOneField(db_column='pd_email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='website.users')),
            ],
            options={
                'db_table': 'patient_disease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('p_email', models.OneToOneField(db_column='p_email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='website.users')),
            ],
            options={
                'db_table': 'patients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicServant',
            fields=[
                ('ps_email', models.OneToOneField(db_column='ps_email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='website.users')),
                ('ps_department', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'public_servant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('r_email', models.OneToOneField(db_column='r_email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='website.publicservant')),
                ('r_total_deaths', models.IntegerField(blank=True, null=True)),
                ('r_total_patients', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'record',
                'managed': False,
            },
        ),
    ]
